FROM python:3.11-slim-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc librdkafka-dev libc6-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir confluent-kafka

COPY src/alert_consumer.py src/alert_consumer.py

CMD ["python", "src/alert_consumer.py"]
